[workspace]
members = [
  "rusqlite_migration",
  "rusqlite_migration_tokio_async",
  "rusqlite_migration_tests",
  "examples/*",
]
exclude = ["examples/target"]

# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"
